name: PHPStan
run-name: Run PHPStan on `${{ github.head_ref }}`

on:
  pull_request:
    paths:
      - 'dev/phpstan-bootstrap.php'
      - 'dev/wordpress-overrides.stub'
      - 'dev/patches/**/*.patch'
      - 'src/**/*.php'
      - '.github/workflows/phpstan.yml'
      - 'phpstan-baseline.neon'
      - 'phpstan.neon'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Detect File Changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            wpcontent:
              - added|modified: 'src/**/*.php'

      - name: Setup PHP
        if: ${{ steps.filter.outputs.wpcontent == 'true' }}
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.2"
          ini-values: "memory_limit=1G"
          coverage: none

      - name: Validate composer.json and composer.lock
        if: ${{ steps.filter.outputs.wpcontent == 'true' }}
        run: composer validate --no-check-publish

      - name: Install Composer dependencies
        if: ${{ steps.filter.outputs.wpcontent == 'true' }}
        run: |
          composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Run PHPStan checks
        if: ${{ steps.filter.outputs.wpcontent == 'true' }}
        run: ./vendor/bin/phpstan analyse ${{ steps.filter.outputs.wpcontent_files }}